[package]
name = "Deadlock"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3.26"
log = "0.4"
pretty_env_logger = "0.5.0"
itertools = "0.12.0"
ansi_term = "0.12.1"

[package.metadata.rust-analyzer]
rustc_private = true